name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"./.coverage/" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format="lcov"
    - name: Recover Test Coverage Report
      run: mkdir ./CoverageReport && cp ./.coverage/**/coverage.info ./CoverageReport
    - name: Publish Coverage to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./CoverageReport/coverage.info
    - name: .NET Publish
      run: dotnet publish --no-build -c Release -o ./bin
    - name: Upload published app
      uses: actions/upload-artifact@v2
      with:
        name: rtchat-server-artifact
        path: ./bin/
