name: Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [ infrastructure/14-add-cd ]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-and-test.yml
        workflow_conclusion: success
        name: rtchat-server-artifact