name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory:"./.coverage/" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format="lcov"
    - name: Recover test coverage report
      run: mkdir ./CoverageReport && cp ./.coverage/**/coverage.info ./CoverageReport
    - name: Publish coverage to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./CoverageReport/coverage.info